#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'vesc==1.0.1','console_scripts','vesc_node'
__requires__ = 'vesc==1.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('vesc==1.0.1', 'console_scripts', 'vesc_node')()
    )
