apiVersion: v0.1
workloads:
  mqtt-broker:
    runtime: podman
    agent: agent_A
    runtimeConfig: |
      image: ghcr.io/izaballa/eclipse-mosquitto:2.0.15 
      commandArgs:
        [
          "sh", "-c",
          "echo 'listener 1883 192.168.1.11\nallow_anonymous true' > /mosquitto/config/mosquitto.conf && mosquitto -c /mosquitto/config/mosquitto.conf"
        ]
      commandOptions: ["--net=host"]
  speed-provider:
    runtime: podman
    agent: agent_A
    dependencies:
      mqtt-broker: ADD_COND_RUNNING
    runtimeConfig: |
      image: ghcr.io/izaballa/speed-provider-mqtt:v1.0.1
      commandOptions:
        - "--net=host"
        - "-e"
        - "MQTT_BROKER_ADDR=192.168.1.11"
        - "-e"
        - "SPEED_PROVIDER_MODE=auto"
  speed-consumer:
    runtime: podman
    agent: infotainment
    dependencies:
      speed-provider: ADD_COND_RUNNING
    runtimeConfig: |
      image: ghcr.io/izaballa/speed-consumer-mqtt:v1.0.2
      commandOptions:
        - "--net=host"
        - "-e"
        - "MQTT_BROKER_ADDR=192.168.1.11"
  mqtt-ros2:
    runtime: podman
    agent: agent_ros2
    dependencies:
      speed-provider: ADD_COND_RUNNING
    runtimeConfig: |
      image: ghcr.io/izaballa/mqtt_ros2:v1.0.1
      commandOptions:
        - "--net=host"
        - "-e"
        - "ROS_IP=192.168.1.12"
        - "-e"
        - "ROS_HOSTNAME=192.168.1.12"
        - "-e"
        - "ROS_DOMAIN_ID=0"
        - "-e"
        - "ROS_DISTRO=foxy"
