apiVersion: v0.1
workloads:
  z-fleet-connector:
    runtime: podman
    agent: agent_A
    controlInterfaceAccess:
      allowRules:
        - type: StateRule
          operation: ReadWrite
          filterMask:
            - "*"
    restartPolicy: NEVER
    runtimeConfig: |
      image: ghcr.io/izaballa/z-fleet-connector:v1.0.30
      commandOptions:
        - "--net=host"
        - "-e"
        - "ZENO_ROUTER_ADDR=tcp/192.168.1.11:7447"
        - "-e"
        - "VIN=1"
