apiVersion: v0.1
workloads:
  fleet-connector:
    runtime: podman
    agent: agent_A
    controlInterfaceAccess:
      allowRules:
        - type: StateRule
          operation: ReadWrite
          filterMask:
            - "*"
    restartPolicy: NEVER
    runtimeConfig: |
      image: ghcr.io/izaballa/fleet-connector:v1.0.1
      commandOptions:
        - "--net=host"
        - "-e"
        - "MQTT_BROKER_ADDR=192.168.1.11"
        - "-e"
        - "VIN=1"